categories: 
  - Machine Learning
description: A powerful and robust low-code library for simplifying machine learning workflows with PyCaret.
name: galaxy_pycaret
owner: goeckslab
long_description: |
  PyCaret is a low-code machine learning library that simplifies the process of building, training, and deploying machine learning models.
  With its comprehensive suite of tools, PyCaret enables users to perform complex tasks such as data preprocessing,
  model selection, hyperparameter tuning, and evaluation, all within a single, intuitive interface. 
  It is designed to be powerful and robust, making it suitable for both beginners and advanced users. 
  Whether you are exploring data for insights, building predictive models, or deploying them into production, 
  PyCaret provides a streamlined workflow that saves time and reduces code complexity.
remote_repository_url: https://github.com/goeckslab/Galaxy-Pycaret
homepage_url: https://github.com/goeckslab/Galaxy-Pycaret

auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for pycaret tool: {{ tool_name }}"
suite:
  name: suite_pycaret
  description: A powerful and robust low-code library for simplifying machine learning workflows with PyCaret.
  long_description: |
    PyCaret is a low-code machine learning library that simplifies the process of building, training, and deploying machine learning models.
    With its comprehensive suite of tools, PyCaret enables users to perform complex tasks such as data preprocessing,
    model selection, hyperparameter tuning, and evaluation, all within a single, intuitive interface. 
    It is designed to be powerful and robust, making it suitable for both beginners and advanced users. 
    Whether you are exploring data for insights, building predictive models, or deploying them into production, 
    PyCaret provides a streamlined workflow that saves time and reduces code complexity.